services:
  - type: web
    name: apsit-wiki
    repo: https://github.com/Didfu/APSITwiki.git
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn APSITwiki.wsgi:application"
    env: python
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: APSITwiki.settings
      - key: SECRET_KEY
        sync: false  # Securely set in Render dashboard
      - key: ALLOWED_HOSTS
        value: ".onrender.com"  # Adjust as needed
      - key: DATABASE_URL
        fromDatabase:
          name: apsit-wiki-db
          property: connectionString
